### ISSUE TITLE
Cannot read property 'WorkerMessageHandler' of undefined

### ISSUE THREAD

**Issue by PlutarcoII** [enovision/ext-pdf-viewer#2]
Hello, Im getting the following message

Uncaught TypeError: Cannot read property 'WorkerMessageHandler' of undefined
at pdf.js?_dc=1507677908727:5
    at HTMLScriptElement.n.onload (pdf.js?_dc=1507677908727:1)

My code... 

Main Controller 
onViewPdf: function(template, url){
       this.createSingleTab(template, {
           title: 'Template: ' + template,
           xtype: 'PdfViewerPdfPanel', // pdf viewer
           layout: 'fit',
           autoScroll: true,
           src: url
       });
    },

Controller
 onClickTemplate: function(){
      var combo = Ext.ComponentQuery.query("combobox")[0];
      var url  = 'http://192.168.1.122:9000/converter/template?temPath='+ combo.getValue();
      this.fireEvent('viewpdf', combo.getValue(), url );
   }

ext-pdf-viewer 
packages/local/ext-pdf-viewer

Extjs v6.5

**Comment by enovision** [comment]
@PlutarcoII , could you please load the latest version I just uploaded and see if that might be an improvement on your problem. If not I would like to see your view and controller code, to see what is going wrong.

**Comment by PlutarcoII** [comment]
Thanks Johan

I did some changes in your package.json beacuse some paths are outdated.
After this change PDF_Viewer works as expected.

```
   {
     "path": "resources/lib/pdf.js/build/minified/web/compatibility.js",
     "includeInBundle": true
   },
   {
     "path": "resources/lib/pdf.js/build/minified/build/pdf.js",
     "includeInBundle": true
   },
   {
     "path": "resources/lib/pdf.js/build/minified/build/pdf.worker.js",
     "includeInBundle": true
   }

```

**Comment by enovision** [comment]
@PlutarcoII , thank you very much, I've updated the package accordingly to your recommendation.
